<ns0:test-suite xmlns:ns0="urn:model.allure.qatools.yandex.ru" start="1562761992413" stop="1562761992413">
  <description>This is the tests collection phase. Failures are modules that failed to collect.</description>
  <name>test_collection_phase</name>
  <title>Collection phase</title>
  <labels/>
  <test-cases>
    <test-case start="1562761992413" status="broken" stop="1562761992413">
      <name>test_tpshop_login</name>
      <failure>
        <message>failed</message>
        <stack-trace>test_tpshop_login.py:21: in &lt;module&gt;
    class TestLogin():
test_tpshop_login.py:33: in TestLogin
    @pytest.mark.parametrize("phone,pwd,code,expect,mark",data_get())
test_tpshop_login.py:13: in data_get
    data()
..\tool\get_data.py:2: in data
    with open('./data/login.txt','r',encoding='utf-8')as f:
E   FileNotFoundError: [Errno 2] No such file or directory: './data/login.txt'</stack-trace>
      </failure>
      <attachments/>
      <labels/>
      <steps/>
    </test-case>
  </test-cases>
</ns0:test-suite>
